import { Car } from '@/types';

export const sampleCars: Omit<Car, '_id' | 'createdAt' | 'updatedAt'>[] = [
  // Các xe hiện có
  {
    name: 'Honda Civic 2024',
    model: 'Civic',
    year: 2024,
    price: 730000000,
    color: 'Trắng Ngọc Trai',
    images: [
      '/images/cars/civic-2024-white-1.jpg',
      '/images/cars/civic-2024-white-2.jpg',
      '/images/cars/civic-2024-white-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.2L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Cảm biến áp suất lốp',
        'Đèn LED toàn bộ',
      ],
    },
    description: 'Honda Civic 2024 với thiết kế thể thao, động cơ mạnh mẽ và tiết kiệm nhiên liệu. Trang bị đầy đủ các tính năng an toàn và tiện nghi hiện đại.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda CR-V 2024',
    model: 'CR-V',
    year: 2024,
    price: 1050000000,
    color: 'Đen Ánh Kim',
    images: [
      '/images/cars/crv-2024-black-1.jpg',
      '/images/cars/crv-2024-black-2.jpg',
      '/images/cars/crv-2024-black-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 7,
      mileage: '7.0L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Cửa sổ trời toàn cảnh',
        'Ghế da cao cấp',
        'Sạc không dây',
      ],
    },
    description: 'Honda CR-V 2024 - SUV 7 chỗ hoàn hảo cho gia đình với không gian rộng rãi, trang bị hiện đại và khả năng vận hành ưu việt.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda Accord 2024',
    model: 'Accord',
    year: 2024,
    price: 1319000000,
    color: 'Bạc Ánh Kim',
    images: [
      '/images/cars/accord-2024-silver-1.jpg',
      '/images/cars/accord-2024-silver-2.jpg',
      '/images/cars/accord-2024-silver-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo va chạm',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp',
        'Hệ thống âm thanh Bose',
        'Sạc không dây',
      ],
    },
    description: 'Honda Accord 2024 - Sedan hạng D cao cấp với thiết kế sang trọng, động cơ mạnh mẽ và trang bị đầy đủ các tiện nghi hiện đại.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda City 2024',
    model: 'City',
    year: 2024,
    price: 559000000,
    color: 'Đỏ Ánh Kim',
    images: [
      '/images/cars/city-2024-red-1.jpg',
      '/images/cars/city-2024-red-2.jpg',
      '/images/cars/city-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '5.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Cảm biến áp suất lốp',
        'Đèn LED',
      ],
    },
    description: 'Honda City 2024 - Sedan hạng B thông minh với thiết kế trẻ trung, tiết kiệm nhiên liệu và giá cả hợp lý.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda HR-V 2024',
    model: 'HR-V',
    year: 2024,
    price: 786000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/hrv-2024-blue-1.jpg',
      '/images/cars/hrv-2024-blue-2.jpg',
      '/images/cars/hrv-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.8L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Cửa sổ trời',
        'Ghế da',
      ],
    },
    description: 'Honda HR-V 2024 - SUV cỡ nhỏ năng động với thiết kế coupe thể thao và khả năng vận hành linh hoạt trong đô thị.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda Pilot 2024',
    model: 'Pilot',
    year: 2024,
    price: 2200000000,
    color: 'Trắng Ngọc Trai',
    images: [
      '/images/cars/pilot-2024-white-1.jpg',
      '/images/cars/pilot-2024-white-2.jpg',
      '/images/cars/pilot-2024-white-3.jpg',
    ],
    specifications: {
      engine: '3.5L V6 i-VTEC',
      transmission: '10-Speed Automatic',
      fuelType: 'Xăng',
      seating: 8,
      mileage: '9.5L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ đỗ xe tự động',
      ],
      features: [
        'Màn hình cảm ứng 12.3 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Cửa sổ trời toàn cảnh',
        'Ghế da cao cấp',
        'Hệ thống âm thanh Bose',
        'Sạc không dây',
        'Cổng USB-C',
      ],
    },
    description: 'Honda Pilot 2024 - SUV hạng sang 8 chỗ với động cơ V6 mạnh mẽ, không gian rộng rãi và trang bị cao cấp nhất.',
    category: 'suv',
    isAvailable: true,
  },
  
  // Thêm xe mới - Hatchback
  {
    name: 'Honda Jazz 2024',
    model: 'Jazz',
    year: 2024,
    price: 480000000,
    color: 'Vàng Chanh',
    images: [
      '/images/cars/jazz-2024-yellow-1.jpg',
      '/images/cars/jazz-2024-yellow-2.jpg',
      '/images/cars/jazz-2024-yellow-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '5.3L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế Magic Seat',
        'Đèn LED',
      ],
    },
    description: 'Honda Jazz 2024 - Hatchback nhỏ gọn với không gian nội thất linh hoạt, tiết kiệm nhiên liệu và thiết kế trẻ trung.',
    category: 'hatchback',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Hatchback 2024',
    model: 'Civic',
    year: 2024,
    price: 820000000,
    color: 'Xanh Lá Đậm',
    images: [
      '/images/cars/civic-hatchback-2024-green-1.jpg',
      '/images/cars/civic-hatchback-2024-green-2.jpg',
      '/images/cars/civic-hatchback-2024-green-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.4L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Cửa sổ trời',
        'Hệ thống âm thanh Bose',
      ],
    },
    description: 'Honda Civic Hatchback 2024 - Phiên bản 5 cửa thể thao của Civic với thiết kế năng động và không gian chứa đồ linh hoạt.',
    category: 'hatchback',
    isAvailable: true,
  },
  
  // Thêm xe mới - Coupe
  {
    name: 'Honda Civic Coupe 2024',
    model: 'Civic',
    year: 2024,
    price: 850000000,
    color: 'Đỏ Thể Thao',
    images: [
      '/images/cars/civic-coupe-2024-red-1.jpg',
      '/images/cars/civic-coupe-2024-red-2.jpg',
      '/images/cars/civic-coupe-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: '6-Speed Manual',
      fuelType: 'Xăng',
      seating: 4,
      mileage: '6.8L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao',
        'Vô lăng bọc da',
      ],
    },
    description: 'Honda Civic Coupe 2024 - Phiên bản 2 cửa thể thao với thiết kế mạnh mẽ, cá tính và trải nghiệm lái phấn khích.',
    category: 'coupe',
    isAvailable: true,
  },
  {
    name: 'Honda Accord Coupe 2024',
    model: 'Accord',
    year: 2024,
    price: 1250000000,
    color: 'Đen Bóng',
    images: [
      '/images/cars/accord-coupe-2024-black-1.jpg',
      '/images/cars/accord-coupe-2024-black-2.jpg',
      '/images/cars/accord-coupe-2024-black-3.jpg',
    ],
    specifications: {
      engine: '2.0L VTEC Turbo',
      transmission: '10-Speed Automatic',
      fuelType: 'Xăng',
      seating: 4,
      mileage: '7.2L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 10 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da thể thao',
        'Hệ thống âm thanh Bose',
        'Cửa sổ trời toàn cảnh',
      ],
    },
    description: 'Honda Accord Coupe 2024 - Coupe hạng sang với thiết kế lịch lãm, động cơ mạnh mẽ và công nghệ tiên tiến.',
    category: 'coupe',
    isAvailable: true,
  },
  
  // Thêm xe mới - Sedan
  {
    name: 'Honda Insight 2024',
    model: 'Insight',
    year: 2024,
    price: 950000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/insight-2024-blue-1.jpg',
      '/images/cars/insight-2024-blue-2.jpg',
      '/images/cars/insight-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC + Electric Motor',
      transmission: 'E-CVT',
      fuelType: 'Hybrid',
      seating: 5,
      mileage: '4.2L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da',
        'Hệ thống âm thanh cao cấp',
      ],
    },
    description: 'Honda Insight 2024 - Sedan hybrid tiết kiệm nhiên liệu với thiết kế hiện đại và công nghệ tiên tiến.',
    category: 'sedan',
    isAvailable: true,
  },
  
  // Thêm xe mới - SUV
  {
    name: 'Honda BR-V 2024',
    model: 'BR-V',
    year: 2024,
    price: 650000000,
    color: 'Bạc Ánh Kim',
    images: [
      '/images/cars/brv-2024-silver-1.jpg',
      '/images/cars/brv-2024-silver-2.jpg',
      '/images/cars/brv-2024-silver-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 7,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế gập linh hoạt',
        'Đèn LED',
      ],
    },
    description: 'Honda BR-V 2024 - SUV 7 chỗ nhỏ gọn với thiết kế đa dụng, phù hợp cho gia đình và di chuyển trong đô thị.',
    category: 'suv',
    isAvailable: true,
  },
  // Thêm xe mới cho mẫu Accord
  {
    name: 'Honda Accord Touring 2024',
    model: 'Accord',
    year: 2024,
    price: 1450000000,
    color: 'Trắng Ngọc Trai',
    images: [
      '/images/cars/accord-touring-2024-white-1.jpg',
      '/images/cars/accord-touring-2024-white-2.jpg',
      '/images/cars/accord-touring-2024-white-3.jpg',
    ],
    specifications: {
      engine: '2.0L VTEC Turbo',
      transmission: '10-Speed Automatic',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '7.0L/100km',
      safety: [
        'Honda SENSING',
        '10 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ đỗ xe tự Động',
      ],
      features: [
        'Màn hình cảm ứng 12.3 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp có sưởi và làm mát',
        'Hệ thống âm thanh Bose 12 loa',
        'Cửa sổ trời toàn cảnh',
        'Sạc không dây',
        'Hệ thống đèn viền nội thất',
      ],
    },
    description: 'Honda Accord Touring 2024 - Phiên bản cao cấp nhất của dòng Accord với đầy đủ tiện nghi, công nghệ và thiết kế sang trọng.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda Accord Sport 2024',
    model: 'Accord',
    year: 2024,
    price: 1250000000,
    color: 'Đỏ San Hô',
    images: [
      '/images/cars/accord-sport-2024-red-1.jpg',
      '/images/cars/accord-sport-2024-red-2.jpg',
      '/images/cars/accord-sport-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.7L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế thể thao',
        'Mâm xe 19 inch',
        'Vô lăng bọc da thể thao',
        'Pedal thể thao',
      ],
    },
    description: 'Honda Accord Sport 2024 - Phiên bản thể thao của Accord với thiết kế năng động, mâm xe lớn và các chi tiết thể thao.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda Accord Hybrid 2024',
    model: 'Accord',
    year: 2024,
    price: 1380000000,
    color: 'Xanh Lá Ánh Kim',
    images: [
      '/images/cars/accord-hybrid-2024-green-1.jpg',
      '/images/cars/accord-hybrid-2024-green-2.jpg',
      '/images/cars/accord-hybrid-2024-green-3.jpg',
    ],
    specifications: {
      engine: '2.0L i-MMD Hybrid',
      transmission: 'E-CVT',
      fuelType: 'Hybrid',
      seating: 5,
      mileage: '4.5L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ giữ làn đường',
      ],
      features: [
        'Màn hình cảm ứng 10 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp',
        'Hệ thống âm thanh cao cấp',
        'Sạc không dây',
        'Cửa sổ trời',
      ],
    },
    description: 'Honda Accord Hybrid 2024 - Phiên bản hybrid tiết kiệm nhiên liệu với công nghệ e:HEV tiên tiến, kết hợp hiệu suất và tiết kiệm nhiên liệu.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda Accord LX 2024',
    model: 'Accord',
    year: 2024,
    price: 1150000000,
    color: 'Xám Ánh Kim',
    images: [
      '/images/cars/accord-lx-2024-gray-1.jpg',
      '/images/cars/accord-lx-2024-gray-2.jpg',
      '/images/cars/accord-lx-2024-gray-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế nỉ cao cấp',
        'Đèn LED',
        'Mâm xe 17 inch',
      ],
    },
    description: 'Honda Accord LX 2024 - Phiên bản tiêu chuẩn với đầy đủ tính năng cơ bản, giá cả hợp lý và vẫn đảm bảo chất lượng Honda.',
    category: 'sedan',
    isAvailable: true,
  },

  // Thêm xe mới cho mẫu Civic
  {
    name: 'Honda Civic RS 2024',
    model: 'Civic',
    year: 2024,
    price: 870000000,
    color: 'Đỏ Thể Thao',
    images: [
      '/images/cars/civic-rs-2024-red-1.jpg',
      '/images/cars/civic-rs-2024-red-2.jpg',
      '/images/cars/civic-rs-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.3L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế thể thao RS',
        'Vô lăng bọc da thể thao',
        'Pedal thể thao',
        'Hệ thống âm thanh Bose',
      ],
    },
    description: 'Honda Civic RS 2024 - Phiên bản thể thao cao cấp của Civic với thiết kế RS đặc trưng, hiệu suất mạnh mẽ và trang bị cao cấp.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda Civic E:HEV 2024',
    model: 'Civic',
    year: 2024,
    price: 950000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/civic-ehev-2024-blue-1.jpg',
      '/images/cars/civic-ehev-2024-blue-2.jpg',
      '/images/cars/civic-ehev-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '2.0L i-MMD Hybrid',
      transmission: 'E-CVT',
      fuelType: 'Hybrid',
      seating: 5,
      mileage: '4.0L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ giữ làn đường',
      ],
      features: [
        'Màn hình cảm ứng 10.2 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp',
        'Hệ thống âm thanh cao cấp',
        'Sạc không dây',
        'Cửa sổ trời toàn cảnh',
      ],
    },
    description: 'Honda Civic E:HEV 2024 - Phiên bản hybrid tiết kiệm nhiên liệu với công nghệ e:HEV tiên tiến, kết hợp hiệu suất và tiết kiệm nhiên liệu.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Type R 2024',
    model: 'Civic',
    year: 2024,
    price: 2200000000,
    color: 'Đỏ Rally',
    images: [
      '/images/cars/civic-typer-2024-red-1.jpg',
      '/images/cars/civic-typer-2024-red-2.jpg',
      '/images/cars/civic-typer-2024-red-3.jpg',
    ],
    specifications: {
      engine: '2.0L VTEC Turbo',
      transmission: '6-Speed Manual',
      fuelType: 'Xăng',
      seating: 4,
      mileage: '8.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Hệ thống kiểm soát lực kéo',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Ghế thể thao Recaro',
        'Vô lăng bọc da Alcantara',
        'Hệ thống âm thanh cao cấp',
        'Bộ mâm 20 inch',
        'Hệ thống xả thể thao',
      ],
    },
    description: 'Honda Civic Type R 2024 - Phiên bản hiệu suất cao nhất của dòng Civic với động cơ 320 mã lực, thiết kế khí động học và công nghệ đua xe.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Sport 2024',
    model: 'Civic',
    year: 2024,
    price: 799000000,
    color: 'Xám Sonic',
    images: [
      '/images/cars/civic-sport-2024-gray-1.jpg',
      '/images/cars/civic-sport-2024-gray-2.jpg',
      '/images/cars/civic-sport-2024-gray-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao',
        'Mâm xe 18 inch',
        'Cánh gió sau thể thao',
      ],
    },
    description: 'Honda Civic Sport 2024 - Phiên bản thể thao với các chi tiết ngoại thất độc đáo, mâm xe lớn hơn và cài đặt khung gầm năng động.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda CR-V Black Edition 2024',
    model: 'CR-V',
    year: 2024,
    price: 1180000000,
    color: 'Đen Tuyền',
    images: [
      '/images/cars/crv-black-2024-black-1.jpg',
      '/images/cars/crv-black-2024-black-2.jpg',
      '/images/cars/crv-black-2024-black-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 7,
      mileage: '7.2L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ đỗ xe tự động',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp',
        'Mâm xe 19 inch đen bóng',
        'Chi tiết ngoại thất đen bóng',
        'Cửa sổ trời toàn cảnh',
        'Sạc không dây',
      ],
    },
    description: 'Honda CR-V Black Edition 2024 - Phiên bản đặc biệt với thiết kế đen toàn thân, mâm xe đen bóng và nội thất đen sang trọng.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda CR-V Hybrid 2024',
    model: 'CR-V',
    year: 2024,
    price: 1250000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/crv-hybrid-2024-blue-1.jpg',
      '/images/cars/crv-hybrid-2024-blue-2.jpg',
      '/images/cars/crv-hybrid-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '2.0L i-MMD Hybrid',
      transmission: 'E-CVT',
      fuelType: 'Hybrid',
      seating: 7,
      mileage: '5.0L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ giữ làn đường',
      ],
      features: [
        'Màn hình cảm ứng 10.2 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da thể thao',
        'Hệ thống âm thanh Bose',
        'Cửa sổ trời toàn cảnh',
        'Sạc không dây',
        'Cổng USB-C',
      ],
    },
    description: 'Honda CR-V Hybrid 2024 - Phiên bản hybrid tiết kiệm nhiên liệu với công nghệ e:HEV tiên tiến, kết hợp hiệu suất và tiết kiệm nhiên liệu.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda CR-V Sport 2024',
    model: 'CR-V',
    year: 2024,
    price: 1150000000,
    color: 'Đỏ Thể Thao',
    images: [
      '/images/cars/crv-sport-2024-red-1.jpg',
      '/images/cars/crv-sport-2024-red-2.jpg',
      '/images/cars/crv-sport-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 7,
      mileage: '7.3L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế thể thao',
        'Mâm xe 19 inch',
        'Vô lăng thể thao',
        'Pedal thể thao',
        'Cánh gió sau thể thao',
      ],
    },
    description: 'Honda CR-V Sport 2024 - Phiên bản thể thao với thiết kế năng động, mâm xe lớn và các chi tiết thể thao.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda CR-V LX 2024',
    model: 'CR-V',
    year: 2024,
    price: 980000000,
    color: 'Bạc Ánh Kim',
    images: [
      '/images/cars/crv-lx-2024-silver-1.jpg',
      '/images/cars/crv-lx-2024-silver-2.jpg',
      '/images/cars/crv-lx-2024-silver-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 7,
      mileage: '7.0L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế nỉ cao cấp',
        'Đèn LED',
        'Mâm xe 17 inch',
      ],
    },
    description: 'Honda CR-V LX 2024 - Phiên bản tiêu chuẩn với đầy đủ tính năng cơ bản, giá cả hợp lý và vẫn đảm bảo chất lượng Honda.',
    category: 'suv',
    isAvailable: true,
  },
  
  // Thêm xe mới cho mẫu City
  {
    name: 'Honda City RS 2024',
    model: 'City',
    year: 2024,
    price: 609000000,
    color: 'Đỏ Thể Thao',
    images: [
      '/images/cars/city-rs-2024-red-1.jpg',
      '/images/cars/city-rs-2024-red-2.jpg',
      '/images/cars/city-rs-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '5.7L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao RS',
        'Vô lăng bọc da thể thao',
        'Pedal thể thao',
        'Mâm xe 16 inch',
      ],
    },
    description: 'Honda City RS 2024 - Phiên bản thể thao cao cấp của City với thiết kế RS đặc trưng, hiệu suất mạnh mẽ và trang bị cao cấp.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda City Hybrid 2024',
    model: 'City',
    year: 2024,
    price: 650000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/city-hybrid-2024-blue-1.jpg',
      '/images/cars/city-hybrid-2024-blue-2.jpg',
      '/images/cars/city-hybrid-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-MMD Hybrid',
      transmission: 'E-CVT',
      fuelType: 'Hybrid',
      seating: 5,
      mileage: '3.9L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp',
        'Đèn LED toàn bộ',
        'Sạc không dây',
      ],
    },
    description: 'Honda City Hybrid 2024 - Phiên bản hybrid tiết kiệm nhiên liệu với công nghệ e:HEV tiên tiến, kết hợp hiệu suất và tiết kiệm nhiên liệu.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda City Sport 2024',
    model: 'City',
    year: 2024,
    price: 589000000,
    color: 'Đen Ánh Kim',
    images: [
      '/images/cars/city-sport-2024-black-1.jpg',
      '/images/cars/city-sport-2024-black-2.jpg',
      '/images/cars/city-sport-2024-black-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '5.6L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao',
        'Mâm xe 16 inch',
        'Cánh gió sau thể thao',
      ],
    },
    description: 'Honda City Sport 2024 - Phiên bản thể thao với các chi tiết ngoại thất độc đáo, mâm xe thể thao và cài đặt khung gầm năng động.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda City LX 2024',
    model: 'City',
    year: 2024,
    price: 529000000,
    color: 'Bạc Ánh Kim',
    images: [
      '/images/cars/city-lx-2024-silver-1.jpg',
      '/images/cars/city-lx-2024-silver-2.jpg',
      '/images/cars/city-lx-2024-silver-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '5.5L/100km',
      safety: [
        'Honda SENSING',
        '4 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế nỉ cao cấp',
        'Đèn LED',
        'Mâm xe 15 inch',
      ],
    },
    description: 'Honda City LX 2024 - Phiên bản tiêu chuẩn với đầy đủ tính năng cơ bản, giá cả hợp lý và vẫn đảm bảo chất lượng Honda.',
    category: 'sedan',
    isAvailable: true,
  },

  // Thêm xe mới cho mẫu Pilot
  {
    name: 'Honda Pilot Elite 2024',
    model: 'Pilot',
    year: 2024,
    price: 1550000000,
    color: 'Đen Ánh Kim',
    images: [
      '/images/cars/pilot-elite-2024-black-1.jpg',
      '/images/cars/pilot-elite-2024-black-2.jpg',
      '/images/cars/pilot-elite-2024-black-3.jpg',
    ],
    specifications: {
      engine: '3.5L V6 i-VTEC',
      transmission: 'Tự động 9 cấp',
      fuelType: 'Xăng',
      seating: 8,
      mileage: '10.5L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ đỗ xe tự động',
        'Hệ thống giám sát áp suất lốp',
      ],
      features: [
        'Màn hình cảm ứng 10.2 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp có sưởi và làm mát',
        'Cửa sổ trời toàn cảnh',
        'Hệ thống âm thanh cao cấp 12 loa',
        'Cửa cốp điện thông minh',
        'Hệ thống giải trí hàng ghế sau',
      ],
    },
    description: 'Honda Pilot Elite 2024 - Phiên bản cao cấp nhất của dòng SUV 8 chỗ Pilot với đầy đủ trang bị cao cấp và công nghệ tiên tiến.',
    category: 'suv',
    isAvailable: true,
  },
  
  // Thêm xe mới cho mẫu Civic Hatchback
  {
    name: 'Honda Civic Hatchback Sport Touring 2024',
    model: 'Civic Hatchback',
    year: 2024,
    price: 850000000,
    color: 'Đỏ Thể Thao',
    images: [
      '/images/cars/civic-hatchback-sport-touring-2024-red-1.jpg',
      '/images/cars/civic-hatchback-sport-touring-2024-red-2.jpg',
      '/images/cars/civic-hatchback-sport-touring-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '10 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ giữ làn đường',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp có sưởi',
        'Cửa sổ trời',
        'Hệ thống âm thanh Bose 12 loa',
        'Sạc không dây',
        'Đèn pha LED thích ứng',
      ],
    },
    description: 'Honda Civic Hatchback Sport Touring 2024 - Phiên bản cao cấp nhất của dòng Civic Hatchback với đầy đủ trang bị cao cấp và công nghệ tiên tiến.',
    category: 'hatchback',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Hatchback Type R 2024',
    model: 'Civic Hatchback',
    year: 2024,
    price: 1200000000,
    color: 'Trắng Ngọc Trai',
    images: [
      '/images/cars/civic-hatchback-type-r-2024-white-1.jpg',
      '/images/cars/civic-hatchback-type-r-2024-white-2.jpg',
      '/images/cars/civic-hatchback-type-r-2024-white-3.jpg',
    ],
    specifications: {
      engine: '2.0L VTEC Turbo',
      transmission: 'Số sàn 6 cấp',
      fuelType: 'Xăng',
      seating: 4,
      mileage: '8.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao Recaro',
        'Vô lăng thể thao',
        'Hệ thống treo thể thao',
        'Mâm xe 20 inch',
        'Cánh gió sau lớn',
        'Hệ thống xả thể thao',
      ],
    },
    description: 'Honda Civic Hatchback Type R 2024 - Phiên bản hiệu suất cao nhất của Honda Civic với động cơ mạnh mẽ, thiết kế thể thao và khả năng vận hành vượt trội.',
    category: 'hatchback',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Hatchback Sport 2024',
    model: 'Civic Hatchback',
    year: 2024,
    price: 750000000,
    color: 'Xám Ánh Kim',
    images: [
      '/images/cars/civic-hatchback-sport-2024-gray-1.jpg',
      '/images/cars/civic-hatchback-sport-2024-gray-2.jpg',
      '/images/cars/civic-hatchback-sport-2024-gray-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.7L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao',
        'Mâm xe 18 inch',
        'Cánh gió sau thể thao',
        'Vô lăng thể thao',
      ],
    },
    description: 'Honda Civic Hatchback Sport 2024 - Phiên bản thể thao với các chi tiết ngoại thất độc đáo, mâm xe thể thao và cài đặt khung gầm năng động.',
    category: 'hatchback',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Hatchback LX 2024',
    model: 'Civic Hatchback',
    year: 2024,
    price: 699000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/civic-hatchback-lx-2024-blue-1.jpg',
      '/images/cars/civic-hatchback-lx-2024-blue-2.jpg',
      '/images/cars/civic-hatchback-lx-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế nỉ cao cấp',
        'Đèn LED',
        'Mâm xe 16 inch',
      ],
    },
    description: 'Honda Civic Hatchback LX 2024 - Phiên bản tiêu chuẩn với đầy đủ tính năng cơ bản, giá cả hợp lý và vẫn đảm bảo chất lượng Honda.',
    category: 'hatchback',
    isAvailable: true,
  },
  {
    name: 'Honda Pilot TrailSport 2024',
    model: 'Pilot',
    year: 2024,
    price: 1450000000,
    color: 'Xanh Rêu',
    images: [
      '/images/cars/pilot-trailsport-2024-green-1.jpg',
      '/images/cars/pilot-trailsport-2024-green-2.jpg',
      '/images/cars/pilot-trailsport-2024-green-3.jpg',
    ],
    specifications: {
      engine: '3.5L V6 i-VTEC',
      transmission: 'Tự động 9 cấp',
      fuelType: 'Xăng',
      seating: 8,
      mileage: '11.2L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hệ thống hỗ trợ địa hình',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da chống thấm nước',
        'Hệ thống treo địa hình',
        'Mâm xe 18 inch địa hình',
        'Tấm bảo vệ gầm xe',
        'Móc kéo tích hợp',
      ],
    },
    description: 'Honda Pilot TrailSport 2024 - Phiên bản địa hình với khả năng off-road vượt trội, trang bị chuyên dụng cho các chuyến phiêu lưu.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda Pilot Touring 2024',
    model: 'Pilot',
    year: 2024,
    price: 1350000000,
    color: 'Bạc Ánh Kim',
    images: [
      '/images/cars/pilot-touring-2024-silver-1.jpg',
      '/images/cars/pilot-touring-2024-silver-2.jpg',
      '/images/cars/pilot-touring-2024-silver-3.jpg',
    ],
    specifications: {
      engine: '3.5L V6 i-VTEC',
      transmission: 'Tự động 9 cấp',
      fuelType: 'Xăng',
      seating: 8,
      mileage: '10.8L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi đa góc',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp',
        'Cửa sổ trời',
        'Hệ thống âm thanh cao cấp',
        'Cửa cốp điện',
      ],
    },
    description: 'Honda Pilot Touring 2024 - Phiên bản cao cấp với nhiều tiện nghi, phù hợp cho gia đình và những chuyến đi dài.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda Pilot EX-L 2024',
    model: 'Pilot',
    year: 2024,
    price: 1250000000,
    color: 'Trắng Ngọc Trai',
    images: [
      '/images/cars/pilot-exl-2024-white-1.jpg',
      '/images/cars/pilot-exl-2024-white-2.jpg',
      '/images/cars/pilot-exl-2024-white-3.jpg',
    ],
    specifications: {
      engine: '3.5L V6 i-VTEC',
      transmission: 'Tự động 9 cấp',
      fuelType: 'Xăng',
      seating: 8,
      mileage: '10.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da',
        'Cửa sổ trời',
        'Hệ thống âm thanh 7 loa',
      ],
    },
    description: 'Honda Pilot EX-L 2024 - Phiên bản tiêu chuẩn với đầy đủ tính năng cơ bản, giá cả hợp lý và vẫn đảm bảo chất lượng Honda.',
    category: 'suv',
    isAvailable: true,
  },
  
  // Thêm xe mới cho mẫu Civic Coupe
  {
    name: 'Honda Civic Coupe Si 2024',
    model: 'Civic Coupe',
    year: 2024,
    price: 899000000,
    color: 'Đỏ Thể Thao',
    images: [
      '/images/cars/civic-coupe-si-2024-red-1.jpg',
      '/images/cars/civic-coupe-si-2024-red-2.jpg',
      '/images/cars/civic-coupe-si-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'Số sàn 6 cấp',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '7.0L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao Si',
        'Vô lăng thể thao',
        'Hệ thống treo thể thao',
        'Mâm xe 18 inch',
        'Cánh gió sau thể thao',
        'Hệ thống xả thể thao',
      ],
    },
    description: 'Honda Civic Coupe Si 2024 - Phiên bản thể thao cao cấp của Civic Coupe với động cơ tăng áp mạnh mẽ và thiết kế thể thao đặc trưng.',
    category: 'coupe',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Coupe Touring 2024',
    model: 'Civic Coupe',
    year: 2024,
    price: 850000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/civic-coupe-touring-2024-blue-1.jpg',
      '/images/cars/civic-coupe-touring-2024-blue-2.jpg',
      '/images/cars/civic-coupe-touring-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ giữ làn đường',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto không dây',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp có sưởi',
        'Cửa sổ trời',
        'Hệ thống âm thanh cao cấp',
        'Sạc không dây',
        'Đèn pha LED thích ứng',
      ],
    },
    description: 'Honda Civic Coupe Touring 2024 - Phiên bản cao cấp nhất của dòng Civic Coupe với đầy đủ trang bị cao cấp và công nghệ tiên tiến.',
    category: 'coupe',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Coupe Sport 2024',
    model: 'Civic Coupe',
    year: 2024,
    price: 780000000,
    color: 'Đen Ánh Kim',
    images: [
      '/images/cars/civic-coupe-sport-2024-black-1.jpg',
      '/images/cars/civic-coupe-sport-2024-black-2.jpg',
      '/images/cars/civic-coupe-sport-2024-black-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.7L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế thể thao',
        'Mâm xe 18 inch',
        'Cánh gió sau thể thao',
        'Vô lăng thể thao',
      ],
    },
    description: 'Honda Civic Coupe Sport 2024 - Phiên bản thể thao với các chi tiết ngoại thất độc đáo, mâm xe thể thao và cài đặt khung gầm năng động.',
    category: 'coupe',
    isAvailable: true,
  },
  {
    name: 'Honda Civic Coupe LX 2024',
    model: 'Civic Coupe',
    year: 2024,
    price: 720000000,
    color: 'Bạc Ánh Kim',
    images: [
      '/images/cars/civic-coupe-lx-2024-silver-1.jpg',
      '/images/cars/civic-coupe-lx-2024-silver-2.jpg',
      '/images/cars/civic-coupe-lx-2024-silver-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Ghế nỉ cao cấp',
        'Đèn LED',
        'Mâm xe 17 inch',
      ],
    },
    description: 'Honda Civic Coupe LX 2024 - Phiên bản tiêu chuẩn với đầy đủ tính năng cơ bản, giá cả hợp lý và vẫn đảm bảo chất lượng Honda.',
    category: 'coupe',
    isAvailable: true,
  },
];
