import { Car } from '@/types';

export const sampleCars: Omit<Car, '_id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Honda Civic 2024',
    model: 'Civic',
    year: 2024,
    price: 730000000,
    color: 'Trắng Ngọc Trai',
    images: [
      '/images/cars/civic-2024-white-1.jpg',
      '/images/cars/civic-2024-white-2.jpg',
      '/images/cars/civic-2024-white-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.2L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Cảm biến áp suất lốp',
        'Đèn LED toàn bộ',
      ],
    },
    description: 'Honda Civic 2024 với thiết kế thể thao, động cơ mạnh mẽ và tiết kiệm nhiên liệu. Trang bị đầy đủ các tính năng an toàn và tiện nghi hiện đại.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda CR-V 2024',
    model: 'CR-V',
    year: 2024,
    price: 1050000000,
    color: 'Đen Ánh Kim',
    images: [
      '/images/cars/crv-2024-black-1.jpg',
      '/images/cars/crv-2024-black-2.jpg',
      '/images/cars/crv-2024-black-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 7,
      mileage: '7.0L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
      ],
      features: [
        'Màn hình cảm ứng 9 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Cửa sổ trời toàn cảnh',
        'Ghế da cao cấp',
        'Sạc không dây',
      ],
    },
    description: 'Honda CR-V 2024 - SUV 7 chỗ hoàn hảo cho gia đình với không gian rộng rãi, trang bị hiện đại và khả năng vận hành ưu việt.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda Accord 2024',
    model: 'Accord',
    year: 2024,
    price: 1319000000,
    color: 'Bạc Ánh Kim',
    images: [
      '/images/cars/accord-2024-silver-1.jpg',
      '/images/cars/accord-2024-silver-2.jpg',
      '/images/cars/accord-2024-silver-3.jpg',
    ],
    specifications: {
      engine: '1.5L VTEC Turbo',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.5L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
        'Cảnh báo va chạm',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 2 vùng',
        'Khởi động bằng nút bấm',
        'Ghế da cao cấp',
        'Hệ thống âm thanh Bose',
        'Sạc không dây',
      ],
    },
    description: 'Honda Accord 2024 - Sedan hạng D cao cấp với thiết kế sang trọng, động cơ mạnh mẽ và trang bị đầy đủ các tiện nghi hiện đại.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda City 2024',
    model: 'City',
    year: 2024,
    price: 559000000,
    color: 'Đỏ Ánh Kim',
    images: [
      '/images/cars/city-2024-red-1.jpg',
      '/images/cars/city-2024-red-2.jpg',
      '/images/cars/city-2024-red-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '5.5L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 8 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Cảm biến áp suất lốp',
        'Đèn LED',
      ],
    },
    description: 'Honda City 2024 - Sedan hạng B thông minh với thiết kế trẻ trung, tiết kiệm nhiên liệu và giá cả hợp lý.',
    category: 'sedan',
    isAvailable: true,
  },
  {
    name: 'Honda HR-V 2024',
    model: 'HR-V',
    year: 2024,
    price: 786000000,
    color: 'Xanh Dương Ánh Kim',
    images: [
      '/images/cars/hrv-2024-blue-1.jpg',
      '/images/cars/hrv-2024-blue-2.jpg',
      '/images/cars/hrv-2024-blue-3.jpg',
    ],
    specifications: {
      engine: '1.5L i-VTEC',
      transmission: 'CVT',
      fuelType: 'Xăng',
      seating: 5,
      mileage: '6.8L/100km',
      safety: [
        'Honda SENSING',
        '6 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera lùi',
      ],
      features: [
        'Màn hình cảm ứng 7 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động',
        'Khởi động bằng nút bấm',
        'Cửa sổ trời',
        'Ghế da',
      ],
    },
    description: 'Honda HR-V 2024 - SUV cỡ nhỏ năng động với thiết kế coupe thể thao và khả năng vận hành linh hoạt trong đô thị.',
    category: 'suv',
    isAvailable: true,
  },
  {
    name: 'Honda Pilot 2024',
    model: 'Pilot',
    year: 2024,
    price: 2200000000,
    color: 'Trắng Ngọc Trai',
    images: [
      '/images/cars/pilot-2024-white-1.jpg',
      '/images/cars/pilot-2024-white-2.jpg',
      '/images/cars/pilot-2024-white-3.jpg',
    ],
    specifications: {
      engine: '3.5L V6 i-VTEC',
      transmission: '10-Speed Automatic',
      fuelType: 'Xăng',
      seating: 8,
      mileage: '9.5L/100km',
      safety: [
        'Honda SENSING',
        '8 túi khí',
        'Hệ thống chống bó cứng phanh ABS',
        'Hệ thống cân bằng điện tử VSA',
        'Camera 360 độ',
        'Cảnh báo điểm mù',
        'Hỗ trợ đỗ xe tự động',
      ],
      features: [
        'Màn hình cảm ứng 12.3 inch',
        'Apple CarPlay/Android Auto',
        'Điều hòa tự động 3 vùng',
        'Khởi động bằng nút bấm',
        'Cửa sổ trời toàn cảnh',
        'Ghế da cao cấp',
        'Hệ thống âm thanh Bose',
        'Sạc không dây',
        'Cổng USB-C',
      ],
    },
    description: 'Honda Pilot 2024 - SUV hạng sang 8 chỗ với động cơ V6 mạnh mẽ, không gian rộng rãi và trang bị cao cấp nhất.',
    category: 'suv',
    isAvailable: true,
  },
];
